server:
  port: 8080

  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/boot_test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
      username:
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver